<Workspace Version="0.9.0.3067" X="0" Y="0" zoom="1" Name="Element.Space" Description="This will retrieve the space in which an element is contained. (if available)" ID="931755f2-b24d-4250-87c7-38100c6991c9" Category="Rhythm.Revit.Elements.Element">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="03cc33cf-4f78-43fe-b1b8-dc95f357c4e6" type="PythonNodeModels.PythonNode" nickname="Python Script" x="759" y="410.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Start Transaction
doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(doc)

#Declare list variables
Space = []
elements = []

#unwrap inputs
for i in IN[0]:
	elements.append(UnwrapElement(i))

#List the "Room" for all phases
for i in elements:
	for phase in doc.Phases:
		if i.CreatedPhaseId == phase.Id:
			try:
				room = i.Space[phase]
				Space.append(room)
			except:
				Space.append(None)
				continue			

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable
OUT = Space</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="093a4377-7a4b-4070-a57c-c7e9d87d9c18" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="454" y="422.218333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Flatten({item});" ShouldFocus="false" />
    <Dynamo.Nodes.Symbol guid="7b7a8724-651c-40bf-9327-acd55d33d695" type="Dynamo.Nodes.Symbol" nickname="Input" x="328" y="454" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="element" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="15eb491d-15c9-437f-9668-65cf74bebb4b" type="Dynamo.Nodes.Output" nickname="Output" x="789" y="506" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="space" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="03cc33cf-4f78-43fe-b1b8-dc95f357c4e6" start_index="0" end="15eb491d-15c9-437f-9668-65cf74bebb4b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="093a4377-7a4b-4070-a57c-c7e9d87d9c18" start_index="0" end="03cc33cf-4f78-43fe-b1b8-dc95f357c4e6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7b7a8724-651c-40bf-9327-acd55d33d695" start_index="0" end="093a4377-7a4b-4070-a57c-c7e9d87d9c18" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>