<Workspace Version="0.9.0.3067" X="-69358.9709381742" Y="-30310.8454468072" zoom="1.1580884251403" Name="Rhythm.3DRoomTags" Description="This node will generate 3D room tags for all rooms in the model. (RFA in extra folder in Dynamo download)" ID="d84be057-2331-4e55-a34d-67b647029ab0" Category="Rhythm.Tools">
  <NamespaceResolutionMap>
    <ClassMap partialName="FamilyType" resolvedName="Revit.Elements.FamilyType" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.DSFunction guid="02fe9810-5492-45ba-96b3-b3f548b6cbb8" type="Dynamo.Nodes.DSFunction" nickname="Element.SetParameterByName" x="61324.5462812799" y="26452.8624179319" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var" />
    <Dynamo.Nodes.DSFunction guid="b3b85dfd-5679-4a31-9a6f-5f58ab4f49b1" type="Dynamo.Nodes.DSFunction" nickname="FamilyInstance.ByPoint" x="60927.5718907077" y="26464.57216822" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.FamilyInstance.ByPoint@Revit.Elements.FamilyType,Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="58e410a0-74ec-4f81-8d86-f6b7b69f2e49" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="61031.8663138189" y="26584.855393194" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="&quot;Name&quot;;&#xA;&quot;Number&quot;;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="9dc256f9-7b08-480d-8cd4-a081760b2ac2" type="Dynamo.Nodes.DSFunction" nickname="Element.SetParameterByName" x="61327.9564981265" y="26589.272696912" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var" />
    <Dynamo.Nodes.Symbol guid="f5522b42-11ab-4de1-a825-86d771af5c5b" type="Dynamo.Nodes.Symbol" nickname="Input" x="60488.0183590675" y="26333.6748272991" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="ThreeDRoomTag : FamilyType" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="2a86eb17-b91a-45a0-961b-231019c6f929" type="Dynamo.Nodes.Symbol" nickname="Input" x="60189.5138074583" y="26538.4171062527" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="RunMe:bool = false" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Function guid="3e33398d-7dcf-438d-88c8-926e42353368" type="Dynamo.Nodes.Function" nickname="Output.Clean" x="61572.7289761808" y="26454.7495713867" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False">
      <ID value="4176dc53-ab69-4804-beb4-e006bece065c" />
      <Name value="Output.Clean" />
      <Description value="This will return a single value or list from one input." />
      <Inputs>
        <Input value="input" />
      </Inputs>
      <Outputs>
        <Output value="result" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Output guid="01685470-824b-4d5c-b476-e1b5bf401bf9" type="Dynamo.Nodes.Output" nickname="Output" x="61752.356260442" y="26494.4462087925" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="ThreeDRoomTags" />
    </Dynamo.Nodes.Output>
    <PythonNodeModels.PythonNode guid="8ec31bed-3001-4dc7-b1ae-cb747b5d3984" type="PythonNodeModels.PythonNode" nickname="Python Script" x="60402.8618183994" y="26535.9254096734" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>#Copyright(c) 2015, Nathan Miller
# The Proving Ground, http://theprovingground.org

import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The input to this node will be stored in the IN[0] variable.

doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

toggle = IN[0]

output = []
rooms = []
names = []
numbers = []
areas = []
levels = []
boundaries = []
locations = []
elementids = []
uniqueids = []

if toggle == True:

	collector = FilteredElementCollector(doc)
	collector.OfCategory(BuiltInCategory.OST_Rooms)
 
	famtypeitr = collector.GetElementIdIterator()
	famtypeitr.Reset()


	for item in famtypeitr:
		elmID = item
		eleminst = doc.GetElement(elmID)
    
		#print eleminst
		if eleminst.Area &gt; 0:
			room = eleminst
			roomname = ''
			for p in room.Parameters:
				if p.Definition.Name == 'Name':		
					roomname = p.AsString()
				if p.Definition.Name == 'Level':				
					level = p.AsValueString()
					
			number = eleminst.Number
			area = eleminst.Area
			
			location = eleminst.Location.Point.ToPoint()
			elementid = eleminst.Id.ToString()
			uniqueid = eleminst.UniqueId
    	
			boptions = Autodesk.Revit.DB.SpatialElementBoundaryOptions()
			boundsegs = room.GetBoundarySegments(boptions)
			boundcurves = []
			for bound in boundsegs:
				crvs = []
				for seg in bound:
					crv = seg.Curve
					crvs.append(Revit.GeometryConversion.RevitToProtoCurve.ToProtoType( crv, True ))
				boundcurves.append(crvs)
    	
			rooms.append(room)
			names.append(roomname)
			numbers.append(number)
			areas.append(area)
			levels.append(level)
			boundaries.append(boundcurves)
			locations.append(location)
			elementids.append(elementid)
			uniqueids.append(uniqueid)
        
	output.append(rooms)
	output.append(names)
	output.append(numbers)
	output.append(areas)
	output.append(levels)
	output.append(locations)
	output.append(boundaries)	
	output.append(elementids)
	output.append(uniqueids)
        
#Assign your output to the OUT variable
OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="7ece50de-a2f6-45ba-804e-f45737817cb8" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="60552.4189976758" y="26536.7889015953" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="x[1];&#xA;x[2];&#xA;x[5];" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="02fe9810-5492-45ba-96b3-b3f548b6cbb8" start_index="0" end="3e33398d-7dcf-438d-88c8-926e42353368" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b3b85dfd-5679-4a31-9a6f-5f58ab4f49b1" start_index="0" end="9dc256f9-7b08-480d-8cd4-a081760b2ac2" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b3b85dfd-5679-4a31-9a6f-5f58ab4f49b1" start_index="0" end="02fe9810-5492-45ba-96b3-b3f548b6cbb8" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="58e410a0-74ec-4f81-8d86-f6b7b69f2e49" start_index="0" end="02fe9810-5492-45ba-96b3-b3f548b6cbb8" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="58e410a0-74ec-4f81-8d86-f6b7b69f2e49" start_index="1" end="9dc256f9-7b08-480d-8cd4-a081760b2ac2" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="f5522b42-11ab-4de1-a825-86d771af5c5b" start_index="0" end="b3b85dfd-5679-4a31-9a6f-5f58ab4f49b1" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2a86eb17-b91a-45a0-961b-231019c6f929" start_index="0" end="8ec31bed-3001-4dc7-b1ae-cb747b5d3984" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3e33398d-7dcf-438d-88c8-926e42353368" start_index="0" end="01685470-824b-4d5c-b476-e1b5bf401bf9" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="8ec31bed-3001-4dc7-b1ae-cb747b5d3984" start_index="0" end="7ece50de-a2f6-45ba-804e-f45737817cb8" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7ece50de-a2f6-45ba-804e-f45737817cb8" start_index="0" end="02fe9810-5492-45ba-96b3-b3f548b6cbb8" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="7ece50de-a2f6-45ba-804e-f45737817cb8" start_index="1" end="9dc256f9-7b08-480d-8cd4-a081760b2ac2" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="7ece50de-a2f6-45ba-804e-f45737817cb8" start_index="2" end="b3b85dfd-5679-4a31-9a6f-5f58ab4f49b1" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel guid="0a766957-6adf-4669-a1ea-844b2881b1ef" text="#Copyright(c) 2015, Nathan Miller&#xD;&#xA;# The Proving Ground, http://theprovingground.org" x="60394.0602266074" y="26646.0970806739" />
  </Notes>
  <Annotations>
    <Dynamo.Models.AnnotationModel guid="69b4fb3b-ac42-4bd8-95ed-f9a275f7d64d" annotationText="Credit for this python script to Nate Miller | Download lunchbox for more awesome stuff like this." left="60392.8618183994" top="26475.9254096734" width="273.557179276351" height="156.86349192194" fontSize="14" InitialTop="26535.9254096734" InitialHeight="126" TextblockHeight="50" backgrouund="#FFC1D676">
      <Models ModelGuid="8ec31bed-3001-4dc7-b1ae-cb747b5d3984" />
      <Models ModelGuid="7ece50de-a2f6-45ba-804e-f45737817cb8" />
    </Dynamo.Models.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>